name: Bug report
description: Report an error or unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the surveydown GitHub repository!
        We are always happy to hear feedback from our users.

        This is the repository for the R package `surveydown`:

        surveydown is under active development!
        If convenient, we'd appreciate if you could check that others haven't already reported the bug in the [repo issues](https://github.com/surveydown-dev/surveydown/issues).

        If you want to ask for a feature, please use the [Feature Requests GitHub Discussions](https://github.com/surveydown-dev/surveydown/discussions/categories/feature-requests).
        If you want to ask for help, please use the [Q&A GitHub Discussions](https://github.com/surveydown-dev/surveydown/discussions/categories/q-a).

        Thank you for using surveydown!

  - type: textarea
    attributes:
      label: Bug description
      description: Description of the bug.
      placeholder: Please describe the bug here.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce this bug.  
        Please include a minimal, fully reproducible example as a self-contained surveydown document or a link to a Git repository.

  - type: textarea
    attributes:
      label: Expected behavior
      description: Tell us what should happen.

  - type: textarea
    attributes:
      label: Actual behavior
      description: Tell us what happens instead.

  - type: textarea
    attributes:
      label: Your environment
      description: |
        Please document the IDE (_e.g._ RStudio, VSCode, NVim), its version, and the operating system you're running (_e.g., MacOS Ventura 13.4, Windows 11, Linux Debian 11, _etc._).
      placeholder: |
        - IDE: RStudio 2023.03.1+446
        - OS: MacOS Ventura 13.4

  - type: markdown
    attributes:
      value: "_Thanks for submitting this bug report!_"
